### ISSUE TITLE
Pushing to S3 error after deployment

### ISSUE THREAD

**Issue by verhagenkava** [darwaishx/worker-safety#2]
Hello,

I followed the instructions provided but after the entire process I am getting an error message in the AWS IoT Console when watching the standard project output. In the environment variable set inside the Lambda function, there is no output shown. The error is the following:

**Pushing to S3 failed: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied**

Could anyone please help?
Thanks a lot!

**Comment by HalEdwa** [comment]
I have the same issue

**Comment by HalEdwa** [comment]
fixed by adding permissions to the deeplens to run the function (both the deeplens and the lambda run on the deeplens need access to s3).

**Comment by verhagenkava** [comment]
Great, thanks!
